//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.10 at 10:07:30 AM GMT-08:00 
//


package edu.woldia.shapetool;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.woldia.shapetool package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.woldia.shapetool
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CircleAreaRequest }
     * 
     */
    public CircleAreaRequest createCircleAreaRequest() {
        return new CircleAreaRequest();
    }

    /**
     * Create an instance of {@link CircleAreaResponse }
     * 
     */
    public CircleAreaResponse createCircleAreaResponse() {
        return new CircleAreaResponse();
    }

    /**
     * Create an instance of {@link SquareAreaRequest }
     * 
     */
    public SquareAreaRequest createSquareAreaRequest() {
        return new SquareAreaRequest();
    }

    /**
     * Create an instance of {@link SquareAreaResponse }
     * 
     */
    public SquareAreaResponse createSquareAreaResponse() {
        return new SquareAreaResponse();
    }

    /**
     * Create an instance of {@link RectangleAreaRequest }
     * 
     */
    public RectangleAreaRequest createRectangleAreaRequest() {
        return new RectangleAreaRequest();
    }

    /**
     * Create an instance of {@link RectangleAreaResponse }
     * 
     */
    public RectangleAreaResponse createRectangleAreaResponse() {
        return new RectangleAreaResponse();
    }

    /**
     * Create an instance of {@link ParallelogramAreaRequest }
     * 
     */
    public ParallelogramAreaRequest createParallelogramAreaRequest() {
        return new ParallelogramAreaRequest();
    }

    /**
     * Create an instance of {@link ParallelogramAreaResponse }
     * 
     */
    public ParallelogramAreaResponse createParallelogramAreaResponse() {
        return new ParallelogramAreaResponse();
    }

    /**
     * Create an instance of {@link TriangleAreaRequest }
     * 
     */
    public TriangleAreaRequest createTriangleAreaRequest() {
        return new TriangleAreaRequest();
    }

    /**
     * Create an instance of {@link TriangleAreaResponse }
     * 
     */
    public TriangleAreaResponse createTriangleAreaResponse() {
        return new TriangleAreaResponse();
    }

}
